"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class stixel_t(object):
    __slots__ = ["x_cm", "y_cm", "z_cm", "h_cm"]

    def __init__(self):
        self.x_cm = 0
        self.y_cm = 0
        self.z_cm = 0
        self.h_cm = 0

    def encode(self):
        buf = BytesIO()
        buf.write(stixel_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhhh", self.x_cm, self.y_cm, self.z_cm, self.h_cm))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != stixel_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return stixel_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = stixel_t()
        self.x_cm, self.y_cm, self.z_cm, self.h_cm = struct.unpack(">hhhh", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if stixel_t in parents: return 0
        tmphash = (0x15fb0f61b834f5b3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if stixel_t._packed_fingerprint is None:
            stixel_t._packed_fingerprint = struct.pack(">Q", stixel_t._get_hash_recursive([]))
        return stixel_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

